# Generated by Django 4.0.2 on 2022-02-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='media/uploads/')),
                ('nome', models.TextField(max_length=100)),
                ('extensao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
